[versions]
minecraft = "26.1.2"
neoForge = "26.1.2.36-beta"
lombokPlugin = "8.7.1"
lombok = "1.18.44"
modDevGradle = "2.0.141"
jsr305 = "3.0.2"
anvillib = "2.0.0+snapshot.336"
bonded-peaks = "0.0.1+build.10"
#flywheel = "1.0.6"
#registrate = "MC1.21-1.3.0+67"
#sable = "1.1.1"
#simulated = "1.1.0"

[libraries]
anvillib-network = { group = "dev.anvilcraft.lib", name = "anvillib-network-neoforge-26.1", version.ref = "anvillib" }
anvillib-wheel = { group = "dev.anvilcraft.lib", name = "anvillib-wheel-neoforge-26.1", version.ref = "anvillib" }
anvillib-config = { group = "dev.anvilcraft.lib", name = "anvillib-config-neoforge-26.1", version.ref = "anvillib" }
anvillib-integration = { group = "dev.anvilcraft.lib", name = "anvillib-integration-neoforge-26.1", version.ref = "anvillib" }
jsr305 = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "jsr305" }
bonded-peaks = { group = "dev.dubhe.bonded", name = "bonded-peaks-26.1.2", version.ref = "bonded-peaks" }
#flywheel = { group = "dev.engine-room.flywheel", name = "flywheel-neoforge-1.21.1", version.ref = "flywheel" }
#registrate = { group = "com.tterrag.registrate", name = "Registrate", version.ref = "registrate" }
#sable = { group = "dev.ryanhcode.sable", name = "sable-neoforge-1.21.1", version.ref = "sable" }
#simulated = { group = "dev.simulated_team.simulated", name = "simulated-neoforge-1.21.1", version.ref = "simulated" }
#offroad = { group = "dev.ryanhcode.offroad", name = "offroad-neoforge-1.21.1", version.ref = "simulated" }
#aeronautics = { group = "dev.eriksonn.aeronautics", name = "aeronautics-neoforge-1.21.1", version.ref = "simulated" }

[bundles]
anvillib = ['anvillib-network', 'anvillib-wheel', 'anvillib-config', 'anvillib-integration']
#simulated = ['flywheel', 'registrate', 'sable', 'simulated', 'offroad', 'aeronautics']

[plugins]
modDevGradle = { id = "net.neoforged.moddev", version.ref = "modDevGradle" }
lombok = { id = "io.freefair.lombok", version.ref = "lombokPlugin" }
